Fix NumpyPlugin binaries path on case-sensitive file systems
Numpy plugin breaks the path of binaries in case-sensitive file systems, giving a FileNotFoundError with option --plugin-enable=numpy while actually the .so file is really available.

Example:
Having numpy file at "/home/johndo/SOMEPROJECT/venv/lib/python3.7/site-packages/numpy/.libs/libopenblasp-r0-8dca6697.3.0.dev.so"

Gives such errror with nuitka:

FileNotFoundError: [Errno 2] No such file or directory: '/home/johndo/someproject/venv/lib/python3.7/site-packages/numpy/.libs/libopenblasp-r0-8dca6697.3.0.dev.so'

This patch fixes the issue so that only the base file name is lower-cased, leaving the rest of the path as-is.